FROM golang:1.26-alpine

WORKDIR /app

RUN apk add --no-cache git build-base ca-certificates tzdata curl && \
    go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

USER nonroot:nonroot

EXPOSE 3000

CMD ["air", "-c", ".air.toml"]
