FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache git build-base ca-certificates tzdata curl && \
    go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 3009

CMD ["air", "-c", ".air.toml"]
